<?php


/**
 * Implements hook_menu().
 */

function nodelist_menu() {
  $items = array();
   $items['admin/config/user-interface/nodelist'] = array(
    'title' => t('Nodelist'),
    'description' => t('View and customize your lists'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodelist_admin_settings'),
    'access arguments' => array('access notification'),
    'type' => MENU_NORMAL_ITEM,
   );// This block-menu will appear in administer settings
  return $items;
}

/**
 * Implements hook_permission().
 */
function nodelist_permission() {
  return array(
    'access nodelist' => array(
      'title' => t('View the administrative nodelist settings'),
      'description' => t('Customizing the nodelist'),
    ),
  );
}


function nodelist_admin_settings() {
// Get an array of node types with internal names as keys and
// "friendly names" as values. E.g.,
  $types = node_type_get_types();
  foreach($types as $node_type) {
   $options[$node_type->type] = $node_type->name;
  }

  $form['nodelist_node_types'] = array(
   '#type' => 'checkboxes',
   '#title' => t('Choose content types to display'),
   '#options' => $options,
   '#default_value' => variable_get('nodelist_node_types', array()),
   '#description' => t('You can choose node types wich will be display'),
  );
  return system_settings_form($form);
}
